name: Tests

on:
  push:
    branches: [main, docs/**]
    paths:
      - "apps/server/**"
      - "apps/web/**"
      - "packages/**"
      - "bun.lockb"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/server/**"
      - "apps/web/**"
      - "packages/**"
      - "bun.lockb"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Run Web + Server Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run server tests
        run: bun run test
        working-directory: ./apps/server

      - name: Run server type check
        run: bun run check-types
        working-directory: ./apps/server

      - name: Run web tests
        run: bun run test
        working-directory: ./apps/web

      - name: Run web type check
        run: bun run check-types
        working-directory: ./apps/web
